name: Backend-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Project Calculator
      run: dotnet build ./backend/ProjectCalculator/src/ProjectCalculator/
    - name: Test Project Calculator
      run: dotnet test ./backend/ProjectCalculator/test/ProjectCalculator.Tests/
