name: Backend-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Project Calculator
      run: dotnet build ./backend/ProjectCalculator/src/ProjectCalculator/
    - name: Test Project Calculator
      run: dotnet test ./backend/ProjectCalculator/test/ProjectCalculator.Tests/

    - name: Build Customer Spread
      run: dotnet build ./backend/CustomerSpreadCalculator/src/
    - name: Test Customer Spread
      run: dotnet test ./backend/CustomerSpreadCalculator/test/CustomerSpreadCalculator.Tests/
  
    - name: Build Contact Us Handler
      run: dotnet build ./backend/ContactUsHandler/src/ContactUsHandler/
    - name: Test Contact Us Handler
      run: dotnet test ./backend/ContactUsHandler/test/ContactUsHandler.Tests/
